# Generated by Django 3.1.3 on 2020-11-22 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Temp',
        ),
    ]
